Server running at http://localhost:3000/
Mongoose connected at: mongodb://localhost/test
SAVED
{ _id: 56a42b322042eca96ff6dcee,
  setId: 1453599538992,
  timestamp: Mon Sep 28 2015 23:57:28 GMT-0700 (PDT),
  accuracy: 50,
  longitude: -118.39543,
  latitude: 34.023222,
  __v: 0 }
SAVED
{ _id: 56a42b322042eca96ff6dcef,
  setId: 1453599538992,
  timestamp: Mon Sep 28 2015 23:57:33 GMT-0700 (PDT),
  accuracy: 50,
  longitude: -118.395431,
  latitude: 34.023243,
  __v: 0 }
post processing!
{ '9537 Culver Blvd': 
   { accessible_wheelchair: true,
     address: '9537 Culver Blvd',
     alcohol: false,
     alcohol_bar: false,
     alcohol_beer_wine: false,
     alcohol_byob: false,
     attire: 'casual',
     category_ids: [ 348, 355, 358 ],
     category_labels: [ [Object], [Object], [Object] ],
     country: 'us',
     cuisine: [ 'Chicken', 'Southern', 'American', 'Fast Food', 'Soul Food' ],
     email: 'info@honeyskettle.com',
     factual_id: '2ad797ab-72dc-4714-85c9-a5786bfedbc9',
     fax: '(310) 202-8063',
     groups_goodfor: true,
     hours: 
      { monday: [Object],
        tuesday: [Object],
        wednesday: [Object],
        thursday: [Object],
        friday: [Object],
        saturday: [Object],
        sunday: [Object] },
     hours_display: 'Mon-Thu 11:00 AM-10:00 PM; Fri-Sat 11:00 AM-11:00 PM; Sun 11:00 AM-10:00 PM',
     kids_goodfor: true,
     latitude: 34.023172,
     locality: 'Culver City',
     longitude: -118.395343,
     meal_breakfast: true,
     meal_cater: true,
     meal_deliver: true,
     meal_dinner: true,
     meal_lunch: true,
     meal_takeout: true,
     name: 'Honey\'s Kettle Fried Chicken',
     neighborhood: [ 'Culver Junction', 'Palms', 'Downtown' ],
     open_24hrs: false,
     options_healthy: true,
     options_lowfat: true,
     options_vegan: true,
     options_vegetarian: true,
     parking: true,
     parking_free: false,
     parking_lot: true,
     parking_street: true,
     payment_cashonly: false,
     postcode: '90232',
     price: 1,
     rating: 4,
     region: 'CA',
     reservations: false,
     seating_outdoor: true,
     smoking: false,
     tel: '(310) 202-5453',
     website: 'http://www.honeyskettle.com',
     wifi: false,
     '$distance': 11.318199,
     distance: [ 11.318199, 9.756921 ] },
  '9531 Culver Blvd': 
   { accessible_wheelchair: true,
     address: '9531 Culver Blvd',
     alcohol: true,
     alcohol_bar: true,
     alcohol_beer_wine: true,
     attire: 'business casual',
     category_ids: [ 357, 356 ],
     category_labels: [ [Object], [Object] ],
     country: 'us',
     cuisine: [ 'Indian' ],
     email: 'info@fordsfillingstation.net',
     factual_id: 'a0bf6d2f-bfd8-4322-8276-fd0d7a2951c6',
     hours: 
      { monday: [Object],
        tuesday: [Object],
        wednesday: [Object],
        thursday: [Object],
        friday: [Object],
        saturday: [Object],
        sunday: [Object] },
     hours_display: 'Mon-Thu 11:30 AM-2:30 PM, 5:30 PM-9:30 PM; Fri 11:30 AM-2:30 PM, 5:30 PM-10:30 PM; Sat 5:30 PM-10:30 PM; Sun 5:30 PM-9:30 PM',
     latitude: 34.023258,
     locality: 'Culver City',
     longitude: -118.395324,
     meal_deliver: true,
     meal_dinner: true,
     meal_takeout: true,
     name: 'Sambar',
     open_24hrs: false,
     options_glutenfree: true,
     parking: true,
     parking_lot: true,
     payment_cashonly: false,
     postcode: '90232',
     price: 3,
     rating: 4,
     region: 'CA',
     reservations: true,
     room_private: true,
     seating_outdoor: true,
     smoking: false,
     tel: '(310) 558-8800',
     website: 'http://www.sambarcc.com',
     '$distance': 10.001147,
     distance: [ 10.001147, 10.557276 ] },
  '405 Hilgard Ave': 
   { address: '405 Hilgard Ave',
     attire: 'casual',
     category_ids: [ 347 ],
     category_labels: [ [Object] ],
     country: 'us',
     cuisine: [ 'Indian', 'Vegetarian', 'Asian', 'Pakistani', 'Cafe' ],
     factual_id: '2de8023d-3700-4ff0-8aea-a2b2e4de9580',
     latitude: 34.023288,
     locality: 'Los Angeles',
     longitude: -118.395428,
     meal_breakfast: true,
     meal_cater: true,
     meal_deliver: false,
     meal_dinner: true,
     meal_lunch: true,
     meal_takeout: true,
     name: 'India Jones Chow Truck',
     neighborhood: [ 'Holmby Hills', 'Westwood' ],
     options_healthy: true,
     options_vegetarian: true,
     parking: true,
     parking_street: true,
     payment_cashonly: true,
     postcode: '90095',
     price: 1,
     region: 'CA',
     tel: '(310) 310-3964',
     website: 'http://www.indiajoneschowtruck.com/',
     wifi: false,
     '$distance': 5.0114107,
     distance: [ 5.0114107, 7.3411894 ] },
  '9523 Culver Blvd': 
   { accessible_wheelchair: true,
     address: '9523 Culver Blvd',
     alcohol: true,
     alcohol_bar: true,
     alcohol_beer_wine: true,
     attire: 'casual',
     category_ids: [ 348, 368, 355 ],
     category_labels: [ [Object], [Object], [Object] ],
     country: 'us',
     cuisine: [ 'American', 'Vegetarian', 'Healthy', 'Salad', 'Organic' ],
     email: 'lacy@tendergreens.com',
     factual_id: '21f65f7f-075d-415a-b3a7-95b93e4a2c8a',
     fax: '(310) 842-8803',
     groups_goodfor: true,
     hours: 
      { monday: [Object],
        tuesday: [Object],
        wednesday: [Object],
        thursday: [Object],
        friday: [Object],
        saturday: [Object],
        sunday: [Object] },
     hours_display: 'Mon-Thu 11:30 AM-9:00 PM; Fri-Sat 11:30 AM-10:00 PM; Sun 11:30 AM-9:00 PM',
     kids_goodfor: true,
     latitude: 34.023354,
     locality: 'Culver City',
     longitude: -118.395219,
     meal_cater: true,
     meal_deliver: true,
     meal_dinner: true,
     meal_lunch: true,
     meal_takeout: true,
     name: 'Tender Greens',
     neighborhood: [ 'Palms', 'Culver Junction', 'Downtown' ],
     open_24hrs: false,
     options_healthy: true,
     options_organic: true,
     options_vegan: true,
     options_vegetarian: true,
     parking: true,
     parking_free: false,
     parking_garage: true,
     parking_lot: true,
     parking_street: true,
     payment_cashonly: false,
     postcode: '90232',
     price: 2,
     rating: 4.5,
     region: 'CA',
     reservations: false,
     seating_outdoor: true,
     smoking: false,
     tel: '(310) 842-8300',
     website: 'http://www.tendergreensfood.com',
     wifi: false,
     '$distance': 23.109915,
     distance: [ 23.109915, 24.36331 ] },
  '9543 Culver Blvd': 
   { accessible_wheelchair: true,
     address: '9543 Culver Blvd',
     alcohol: true,
     alcohol_bar: true,
     alcohol_beer_wine: true,
     attire: 'casual',
     category_ids: [ 348, 340, 342 ],
     category_labels: [ [Object], [Object], [Object] ],
     country: 'us',
     cuisine: [ 'American', 'Organic', 'Bakery', 'Cafe', 'Contemporary' ],
     email: 'info@akasharestaurant.com',
     factual_id: '0185f779-8d03-40ba-829d-3c31405a86fb',
     fax: '(213) 624-9746',
     groups_goodfor: true,
     hours: 
      { monday: [Object],
        tuesday: [Object],
        wednesday: [Object],
        thursday: [Object],
        friday: [Object],
        saturday: [Object],
        sunday: [Object] },
     hours_display: 'Mon-Thu 8:00 AM-9:30 PM; Fri 8:00 AM-10:30 PM; Sat 9:00 AM-10:30 PM; Sun 10:30 AM-9:00 PM',
     kids_goodfor: true,
     latitude: 34.023038,
     locality: 'Culver City',
     longitude: -118.395462,
     meal_breakfast: true,
     meal_cater: true,
     meal_deliver: true,
     meal_dinner: true,
     meal_lunch: true,
     meal_takeout: true,
     name: 'Akasha',
     neighborhood: [ 'Palms', 'Downtown', 'Culver Junction' ],
     open_24hrs: false,
     options_glutenfree: true,
     options_healthy: true,
     options_organic: true,
     options_vegan: true,
     options_vegetarian: true,
     parking: true,
     parking_free: false,
     parking_garage: true,
     parking_lot: true,
     parking_street: true,
     parking_valet: true,
     payment_cashonly: false,
     postcode: '90232',
     price: 3,
     rating: 4,
     region: 'CA',
     reservations: true,
     room_private: true,
     seating_outdoor: true,
     smoking: false,
     tel: '(310) 845-1700',
     website: 'http://www.akasharestaurant.com',
     wifi: true,
     '$distance': 22.97333,
     distance: [ 22.97333, 20.671347 ] },
  '9546 Washington Blvd': 
   { accessible_wheelchair: true,
     address: '9546 Washington Blvd',
     alcohol: true,
     alcohol_bar: true,
     alcohol_beer_wine: true,
     attire: 'casual',
     category_ids: [ 348 ],
     category_labels: [ [Object] ],
     country: 'us',
     cuisine: [ 'American', 'Pub Food', 'Pizza', 'Tapas', 'Burgers' ],
     email: 'joinus@rushstreetculvercity.com',
     factual_id: '04f707f0-6144-4230-ab0a-7d323536d901',
     fax: '(310) 837-9548',
     groups_goodfor: true,
     hours: 
      { monday: [Object],
        tuesday: [Object],
        wednesday: [Object],
        thursday: [Object],
        friday: [Object],
        saturday: [Object],
        sunday: [Object] },
     hours_display: 'Open Daily 11:00 AM-11:00 PM',
     kids_goodfor: true,
     latitude: 34.023002,
     locality: 'Culver City',
     longitude: -118.394985,
     meal_breakfast: true,
     meal_deliver: true,
     meal_dinner: true,
     meal_lunch: true,
     meal_takeout: true,
     name: 'Rush Street',
     neighborhood: [ 'Culver Junction', 'Palms', 'Downtown' ],
     open_24hrs: false,
     options_healthy: true,
     options_organic: true,
     options_vegetarian: true,
     parking: true,
     parking_free: false,
     parking_garage: true,
     parking_lot: true,
     parking_street: true,
     parking_valet: true,
     payment_cashonly: false,
     postcode: '90232',
     price: 2,
     rating: 4,
     region: 'CA',
     reservations: true,
     room_private: true,
     seating_outdoor: true,
     smoking: false,
     tel: '(310) 837-9546',
     website: 'http://www.rushstreetculvercity.com',
     wifi: false,
     '$distance': 49.067425,
     distance: [ 49.067425, 47.752968 ] },
  '9501 Culver Blvd': 
   { address: '9501 Culver Blvd',
     alcohol: true,
     alcohol_bar: true,
     alcohol_beer_wine: true,
     category_ids: [ 347 ],
     category_labels: [ [Object] ],
     country: 'us',
     cuisine: [ 'Italian', 'Cafe', 'Coffee', 'Tea' ],
     factual_id: '2b66f550-0355-012f-b33e-003048cacd48',
     latitude: 34.023487,
     locality: 'Culver City',
     longitude: -118.395047,
     name: 'Ugo: An Italian Bar',
     neighborhood: [ 'Downtown', 'Culver Junction', 'Palms' ],
     postcode: '90232',
     price: 2,
     rating: 3,
     region: 'CA',
     seating_outdoor: true,
     tel: '(310) 204-1222',
     website: 'http://cafeugo.com',
     '$distance': 44.592865,
     distance: [ 44.592865, 45.980125 ] } }
final result:[object Object]
[0mPOST /restaurant/simple [32m200 [0m295.532 ms - -[0m
SAVED
{ _id: 56a42b382042eca96ff6dcf0,
  setId: 1453599544063,
  timestamp: Mon Sep 28 2015 23:57:28 GMT-0700 (PDT),
  accuracy: 50,
  longitude: -118.39543,
  latitude: 34.023222,
  __v: 0 }
SAVED
{ _id: 56a42b382042eca96ff6dcf1,
  setId: 1453599544063,
  timestamp: Mon Sep 28 2015 23:57:33 GMT-0700 (PDT),
  accuracy: 50,
  longitude: -118.395431,
  latitude: 34.023243,
  __v: 0 }
